### ISSUE TITLE
BigNumber: Support numbers (not just big integers)

### ISSUE THREAD

**Issue by sectore** [f-o-a-m/purescript-eth-core#7]
Currently we can do the following:
```
divide (embed 1) (embed 1000) `shouldEqual` embed 0
```

It would be nice to do something like this:
```
divide (embed 1) (embed 1000) `shouldEqual` embedNumber 0.001
```

**Comment by martyall** [comment]
It's by design that a `BigNumber` (maybe despite it's name) is always a whole number. There are lots of things that we do with them that make no sense for a float. Like, how do you hex en/decode a float? How do you rlp encode a float? It can be argued that we should change the name, but we can't allow non-integers in this type.

We switched to using bn.js from bignumber.js because it plays better with other core ethereum libs (like secpk256.js, rlp.js, eth-js-utils.js etc. 

If you would like something that is able to handle floating points etc, we can think about making a separate type that represents that. 

If someone wants to put in work, we can probably use this https://github.com/sharkdp/purescript-bigints/blob/master/src/Data/BigInt.purs and just convert to bn.js types in javascript before doing things like RLP

**Comment by sectore** [comment]
Ok, I see you point. For anybody else who might be interested, here are some more details to get a better picture about the reason for opening this issue: 

[`formatValue`](https://github.com/f-o-a-m/purescript-web3/blob/8af4b46aa4766366bfedbe9f186909cd02b8577c/src/Network/Ethereum/Web3/Types/EtherUnit.purs#L62-L63) function of `purescript-web3` is using [`BigNumber`](https://github.com/f-o-a-m/purescript-eth-core/blob/0e43f14a1d51deb50106c9a72f99008e48c7aca2/src/Network/Ethereum/Core/BigNumber.purs) implementation of `purescript-eth-core`. 

If you are trying to run
```
formatValue (convert (mkValue (embed 1000000000000000) :: Value Wei) :: Value Ether)
```
the result will be `0` instead of `0.001`. With that the result is incorrect (`1000000000000000 Wei` == `0.01 Ether` but not `0 Ether`). The reason for that issue is not the implementation of `formatValue`, but the fact that `bn.js` is using big integers only.

It would be nice to have similar thing like [`toFormat`](https://mikemcl.github.io/bignumber.js/#toFor) of  `bignumber.js` to support a better formatting of `BigNumbers` values such as `Value Wei`, `Value Ether` etc. For that a support of numbers (not integers only) might be needed in any way. So your suggestion about creating a separate type for representing floating points are very welcome!

P.S. If you are thinking this is more a `purescript-web3` issue, then I can move that issue there.
